param(
    [Parameter(Mandatory = $true)]
    [string]$TombEngineRoot,

    [string]$OutputPath = "docs/status/TEN_Object_OCB_SourceScan_Generated.md",

    [int]$ContextLines = 3
)

Set-StrictMode -Version Latest
$ErrorActionPreference = "Stop"

function Get-RelativePath {
    param(
        [string]$BasePath,
        [string]$FullPath
    )

    $baseUri = [System.Uri]((Resolve-Path $BasePath).Path.TrimEnd([System.IO.Path]::DirectorySeparatorChar) + [System.IO.Path]::DirectorySeparatorChar)
    $fileUri = [System.Uri]((Resolve-Path $FullPath).Path)
    return [System.Uri]::UnescapeDataString($baseUri.MakeRelativeUri($fileUri).ToString()).Replace('/', [System.IO.Path]::DirectorySeparatorChar)
}

function Get-SourceGroup {
    param([string]$RelativePath)

    $path = $RelativePath.Replace('/', '\')

    if ($path -match "Objects\\TR1\\") { return "TR1" }
    if ($path -match "Objects\\TR2\\") { return "TR2" }
    if ($path -match "Objects\\TR3\\") { return "TR3" }
    if ($path -match "Objects\\TR4\\") { return "TR4" }
    if ($path -match "Objects\\TR5\\") { return "TR5" }
    if ($path -match "Objects\\Effects\\") { return "Effects / Emitters" }
    if ($path -match "Objects\\Generic\\") { return "Generic" }
    if ($path -match "Game\\") { return "Core" }

    return "Other"
}

function Get-MatchKind {
    param([string]$Line)

    if ($Line -match "TestOcb\s*\(") { return "TestOcb" }
    if ($Line -match "RemoveOcb\s*\(") { return "RemoveOcb" }
    if ($Line -match "ClearAllOcb\s*\(") { return "ClearAllOcb" }
    if ($Line -match "TriggerFlags\s*(&|\|)") { return "TriggerFlags bitwise" }
    if ($Line -match "TriggerFlags\s*(==|!=|<=|>=|<|>)") { return "TriggerFlags comparison" }
    if ($Line -match "switch\s*\([^\)]*TriggerFlags") { return "TriggerFlags switch" }
    if ($Line -match "case\s+[-]?[0-9]+\s*:") { return "Numeric case" }
    if ($Line -match "ItemFlags|GetFlagField|TestFlagField|SetFlagField|ClearFlags") { return "ItemFlags related" }

    return "Other";
}

function Get-NumericEvidence {
    param([string]$Line)

    $matches = [regex]::Matches($Line, "(?<![A-Za-z0-9_])-?\d+(?![A-Za-z0-9_])")
    if ($matches.Count -eq 0) { return "" }

    return (($matches | ForEach-Object { $_.Value }) | Select-Object -Unique) -join ", "
}

if (!(Test-Path $TombEngineRoot)) {
    throw "TombEngineRoot does not exist: $TombEngineRoot"
}

$sourceFiles = Get-ChildItem -Path $TombEngineRoot -Recurse -File -Include *.cpp,*.h,*.hpp,*.inl |
    Where-Object {
        $_.FullName -match "[\\/]TombEngine[\\/]" -and
        ($_.FullName -match "[\\/]Objects[\\/]" -or $_.FullName -match "[\\/]Game[\\/]items\.(cpp|h)$")
    } |
    Sort-Object FullName

$patterns = @(
    "TriggerFlags",
    "TestOcb\s*\(",
    "RemoveOcb\s*\(",
    "ClearAllOcb\s*\(",
    "ItemFlags",
    "GetFlagField\s*\(",
    "TestFlagField\s*\(",
    "SetFlagField\s*\(",
    "ClearFlags\s*\("
)

$findings = New-Object System.Collections.Generic.List[object]

foreach ($file in $sourceFiles) {
    $relativePath = Get-RelativePath -BasePath $TombEngineRoot -FullPath $file.FullName
    $lines = Get-Content -Path $file.FullName

    for ($i = 0; $i -lt $lines.Count; $i++) {
        $line = $lines[$i]
        $hasMatch = $false

        foreach ($pattern in $patterns) {
            if ($line -match $pattern) {
                $hasMatch = $true
                break
            }
        }

        if (!$hasMatch) {
            continue
        }

        $start = [Math]::Max(0, $i - $ContextLines)
        $end = [Math]::Min($lines.Count - 1, $i + $ContextLines)
        $context = New-Object System.Collections.Generic.List[string]

        for ($j = $start; $j -le $end; $j++) {
            $prefix = if ($j -eq $i) { ">" } else { " " }
            $context.Add(("{0}{1}: {2}" -f $prefix, ($j + 1), $lines[$j].TrimEnd()))
        }

        $findings.Add([pscustomobject]@{
            Group = Get-SourceGroup -RelativePath $relativePath
            File = $relativePath
            Line = $i + 1
            Kind = Get-MatchKind -Line $line
            NumericEvidence = Get-NumericEvidence -Line $line
            Code = $line.Trim()
            Context = ($context -join "`n")
        })
    }
}

$builder = New-Object System.Text.StringBuilder
[void]$builder.AppendLine("# TEN Object OCB Source Scan - Generated")
[void]$builder.AppendLine("")
[void]$builder.AppendLine("Generated by `docs/tools/ScanTenOcbSource.ps1`.")
[void]$builder.AppendLine("")
[void]$builder.AppendLine("This report is source evidence only. It does not assign final meanings automatically.")
[void]$builder.AppendLine("")
[void]$builder.AppendLine("## Summary")
[void]$builder.AppendLine("")
[void]$builder.AppendLine("| Group | Matches |")
[void]$builder.AppendLine("| --- | ---: |")

$findings | Group-Object Group | Sort-Object Name | ForEach-Object {
    [void]$builder.AppendLine(("| {0} | {1} |" -f $_.Name, $_.Count))
}

[void]$builder.AppendLine("")
[void]$builder.AppendLine("## Findings")
[void]$builder.AppendLine("")

foreach ($group in ($findings | Group-Object Group | Sort-Object Name)) {
    [void]$builder.AppendLine(("### {0}" -f $group.Name))
    [void]$builder.AppendLine("")

    foreach ($entry in ($group.Group | Sort-Object File, Line)) {
        [void]$builder.AppendLine(("#### `{0}:{1}`" -f $entry.File, $entry.Line))
        [void]$builder.AppendLine("")
        [void]$builder.AppendLine(("- Kind: {0}" -f $entry.Kind))
        if (![string]::IsNullOrWhiteSpace($entry.NumericEvidence)) {
            [void]$builder.AppendLine(("- Numeric evidence: `{0}`" -f $entry.NumericEvidence))
        }
        [void]$builder.AppendLine(("- Code: `{0}`" -f $entry.Code.Replace("`", "``")))
        [void]$builder.AppendLine("")
        [void]$builder.AppendLine("```cpp")
        [void]$builder.AppendLine($entry.Context)
        [void]$builder.AppendLine("```")
        [void]$builder.AppendLine("")
    }
}

$outputDirectory = Split-Path -Path $OutputPath -Parent
if (![string]::IsNullOrWhiteSpace($outputDirectory) -and !(Test-Path $outputDirectory)) {
    New-Item -ItemType Directory -Path $outputDirectory | Out-Null
}

$builder.ToString() | Set-Content -Path $OutputPath -Encoding UTF8
Write-Host ("Wrote {0} findings to {1}" -f $findings.Count, $OutputPath)
